# Generated by Django 5.2 on 2025-04-26 02:12

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Contenido'),
        ),
    ]
