// ... existing code ...
                // Modificar las instrucciones personalizadas en la configuración de RIPER5
                // await vscode.workspace.getConfiguration().update('riper5.customInstructions', customInstructions, vscode.ConfigurationTarget.Global);
// ... existing code ... 