# Generated by Django 5.2 on 2025-04-25 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 0, 40, 32, 33175, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
